// src/components/Footer.jsx
import GitHubLogo from "../assets/github.svg";
import LinkedInLogo from "../assets/linkedin.svg";
import EmailLogo from "../assets/email.svg";

export function Footer() {
    return (
        <>
            <div className="external-links">
                <div>
                    <a href="https://github.com/s-Aura-v"> <img src={GitHubLogo} alt={"github: /s-aura-v"}/> </a>
                </div>
                <div>
                    <a href="https://www.linkedin.com/in/s-aura-v/"> <img src={LinkedInLogo}
                                                                          alt={"linkedin: in/s-aura-v"}/> </a>
                </div>
                <div>
                    <a href="mailto:sauravl2004@gmail.com"> <img src={EmailLogo} alt={"email: sauravl2004@gmail.com"}/>
                    </a>
                </div>
            </div>
            <div className="footer">
                Saurav Lamichhane. 2024.
            </div>
        </>
    )
}

// src/components/Footer.svelte
<script>
    import '../styles/footer.css'

    let links = [
        {name: 'Github', icon: 'images/icons/github-svgrepo-com.svg', url: 'https://github.com/s-Aura-v'},
        {name: 'LinkedIn', icon: 'images/icons/linkedin-svgrepo-com.svg', url: 'https://linkedin.com/in/s-aura-v'},
        {name: 'Email', icon: 'images/icons/email-svgrepo-com.svg', url: ''}
    ]
</script>

<main>
    <div class="social-links">
        {#each links as link, index}
            <a href={link.url} target="_blank" rel="noopener">
                <img src={link.icon} alt={link.name}/>
            </a>
        {/each}

    </div>

    <div class="footer-info">
        Saurav Lamichhane. 2024-2025.
    </div>
</main>
